version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-database
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: deliverydb
    volumes:
      - delivery:/var/lib/mysql
volumes:
  delivery:

#docker-compose -f stack.yml up
